version: '3'
services:
  ubuntu:
    build: ./ubuntu
    restart: 'no'
    ports:
      - '${APACHE_PORT}:80'
    volumes:
      - '../:/var/www'
      - './php/php.ini:/etc/php/7.3/apache2/php.ini'
      - './php/php.ini:/etc/php/7.3/cli/php.ini'
      - './apache2/apache2.conf:/etc/apache2/apache2.conf'
      - './apache2/ports.conf:/etc/apache2/ports.conf'
      - './apache2/000-default.conf:/etc/apache2/sites-enabled/000-default.conf'
    links:
      - mysql
  mysql:
    image: 'mysql:8.0.21'
    command: '--default-authentication-plugin=mysql_native_password'
    restart: 'no'
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - './mysql/data:/var/lib/mysql'
      - './mysql/logs:/var/log/mysql'
      - './mysql/my.cnf:/etc/mysql/conf.d/my.cnf'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DB}'
